language: php

php:
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - composer install
  - php -S localhost:8000 httpdocs/index.php &
  - sleep 3

script:
  - ./vendor/bin/behat
  - ./vendor/bin/phpspec run
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml